config/routes.rb
Fr33::Application.routes.draw do
  resources :categories

  get "home/index"
  devise_for :users
  resources :news

  root to: "home#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :news, :class_name=>News
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  def permitted_params
    params.permit(:category => [:title, :description])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news = News.all
  end
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :news_id %><br>
    <%= f.number_field :news_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>News</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= category.news_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>News:</strong>
  <%= @category.news_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>

    <% @news.each do |news| %>
        <%= news.title %>
        <%= news.body %>
        <%= news.category_id %>
        <%= news.user_id %>
        <%= link_to 'Show', news %>
      </tr>
    <% end %>

app/views/layouts/application.html.erb
<html>
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en" itemscope itemtype="http://schema.org/Product"> <!--<![endif]-->

<head>
  <meta charset="utf-8">

  <title>FR33</title>
  <meta name="description" content="Iranian free software users">
  <meta name="keywords" content="free software open source Iran" />

  <!-- Facebook Metadata /-->
  <meta property="og:title" content="Personal website of b3hnam !"/>
  <meta property="og:type" content="article"/>
  <meta property="og:image" content="images/thumbnail.jpg"/>
  <meta property="og:url" content="http://b3hnam.com"/>
  <meta property="og:description" content=""/>

  <!-- Google+ Metadata /-->
  <meta itemprop="name" content="b3hnam.com">
  <meta itemprop="description" content="">
  <meta itemprop="image" content="">

  <!-- Facebook Metadata /-->
  <meta name="twitter:card" content="summary">

  <link rel="author" href="https://plus.google.com/109827519454759142474">

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_link_tag    "print", media: "print", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>


  <body>
    <div class="navbar" >
       <a class="toggle" gumby-trigger=".navbar > .row > #navigation > ul" href="#"><i class="icon-menu"></i></a>
      <div class="row">
	<div class="four columns">
	  <h1 class="logo">FR33</h1>
	</div>
	<div id="navigation" class="eight columns" >

	</div>
      </div>
    </div>

    <section id="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </section>

    <div class="footer">
    </div>

  </body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Category</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.body %></td>
        <td><%= news.category_id %></td>
        <td><%= news.user_id %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @news.body %>
</p>

<p>
  <strong>Category:</strong>
  <%= @news.category_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @news.user_id %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>